name: Is the list of filenames relevant?
description: A GitHub action that takes a list of files and decides if they are relevant
inputs:
  filenames:
    description: "A comma separated list of filenames"
    type: string
    required: true
  includes:
    description: "A multi-line list of globs that are relevant"
    type: string
    required: false
    default: ""
  excludes:
    description: "A multi-line list of globs that are to be ignored as they are not relevant"
    type: string
    required: false
    default: ""
  config:
    description: "A JSON config string which defines multiple relevance tests"
    type: string
    required: false
    default: ""
outputs:
  relevant:
    description: "yes/no string indicating whether step is relevant or not"
    value: ${{ steps.relevant.outputs.result }}
  relevant-files:
    description: "comma separated list of relevant files"
    value: ${{ steps.relevant.outputs.relevant-files }}
runs:
  using: "composite"
  steps:
    - name: Filter filenames by includes and excludes
      id: relevant
      shell: python
      run: |
        import os
        import fnmatch
        import re
        import json

        filenamesInput = "${{ inputs.filenames }}" or "${{ github.event.inputs.filenames }}"
        includesInput = '''${{ inputs.includes }}''' or '''${{ github.event.inputs.includes }}'''
        excludesInput = '''${{ inputs.excludes }}''' or '''${{ github.event.inputs.excludes }}'''
        configInput = '''${{ inputs.config }}''' or '''${{ github.event.inputs.config }}'''

        def translateGlobToRegex(globPattern):
          prefix = "^" if globPattern.startswith("/") else ""
          return prefix + fnmatch.translate(globPattern) + "$"

        def isRelevant(filenamesStr, includesStr, excludesStr):
          filenamesArr = ([], filenamesStr.split(","))[len(filenamesStr) > 0]
          includesArr = ([], includesStr.splitlines())[len(includesStr) > 0]
          excludesArr = ([], excludesStr.splitlines())[len(excludesStr) > 0]

          includesCleanArr = map(str.strip, includesArr)
          excludesCleanArr = map(str.strip, excludesArr)

          includesList = list(includesCleanArr)
          excludesList = list(excludesCleanArr)

          includesRegexArr = map(translateGlobToRegex, includesList)
          excludesRegexArr = map(translateGlobToRegex, excludesList)

          includesRegexList = list(includesRegexArr)
          excludesRegexList = list(excludesRegexArr)

          def includesFilter(filename):
            if len(includesRegexList) == 0:
              return True;

            print("checking whether '" + filename + "' included in '" + ",".join(includesList) + "'")

            for includeRegex in includesRegexList:
              print("checking: '" + filename + "' against '" + includeRegex + "'")

              if re.search(r"" + includeRegex, filename):
                print("match found")
                return True
              else:
                print("no match")

            print("'" + filename + "' not included by '" + ",".join(includesList) + "'")

            return False

          def excludesFilter(filename):
            if len(excludesRegexList) == 0:
              return True;

            print("checking whether '" + filename + "' excluded by '" + ",".join(excludesList) + "'")

            for excludeRegex in excludesRegexList:
              print("checking: '" + filename + "' against '" + excludeRegex + "'")

              if re.search(r"" + excludeRegex, filename):
                print("match found")
                return False
              else:
                print("no match")

            print("'" + filename + "' not excluded by '" + ",".join(excludesList) + "'")

            return True

          # Throw away filenames that don't match one of the include patterns
          filenamesArr = list(filter(includesFilter, filenamesArr))

          # Throw away filenames that match any exclude pattern
          filenamesArr = filter(excludesFilter, filenamesArr)

          resultsList = list(filenamesArr)

          print('filenamesInput: ' + filenamesInput)
          print('includesList: ' + ",".join(includesList))
          print('excludesList: ' + ",".join(excludesList))

          result = ('no', 'yes')[len(resultsList) > 0]
          resultListStr = ",".join(resultsList)

          print('Is relevant? ' + result)
          print('Relevant files: ' + resultListStr)

          return result, resultListStr

        result, resultListStr = isRelevant(filenamesInput, includesInput, excludesInput)

        if len(configInput) > 0:
          print('Config detected: ' + configInput)

          configArr = json.loads(configInput)
          resultsList = []

          for configItem in configArr:
            itemName = configItem['name']
            itemIncludes = configItem.get('includes', "")
            itemExcludes = configItem.get('excludes', "")
            print(itemName + ": includes: '" + itemIncludes + "' excludes: '" + itemExcludes + "'")
            result, resultListStr = isRelevant(resultListStr, itemIncludes, itemExcludes)
            print(itemName + ": result: '" + result + "' files: '" + resultListStr + "'")
            resultsList += [result]
          
          resultsListStr = ",".join(resultsList)

          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
            print(f'result={resultsListStr}', file=fh)
        else:
          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
            print(f'result={result}', file=fh)

        with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
          print(f'relevant-files={resultListStr}', file=fh)

        file = open(os.environ['GITHUB_OUTPUT'], "r");

        print("GITHUB_OUTPUT:");
        print(file.read());

        file.close();
