name: Validates output from is-relevant tests
inputs:
  relevant-expected:
    description: "Expected yes/no string"
    type: string
    required: true
  relevant-actual:
    description: "Actual yes/no string"
    type: string
    required: true
  relevant-files-expected:
    description: "Expected comma separated list of filenames"
    type: string
    required: true
  relevant-files-actual:
    description: "Actual comma separated list of filenames"
    type: string
    required: true
runs:
  using: "composite"
  steps:
    - name: Validate relevant output
      shell: "bash"
      run: |
        actual="${{ inputs.relevant-actual }}"
        expected="${{ inputs.relevant-expected }}"
        if [ $actual != $expected ]
        then
          echo "::error::Not expected result, expected '${expected}', actual '${actual}'"
          exit 1
        fi
    - name: Validate relevant-files output
      shell: "bash"
      run: |
        validate_file_list () {
          actual=$1
          expected=$2

          actual_sorted=$(echo "$actual" | jq 'split(",") | sort_by(.) | join(",")')
          expected_sorted=$(echo "$expected" | jq 'split(",") | sort_by(.) | join(",")')

          if [ $actual_sorted != $expected_sorted ]
          then
            echo "::error::Not expected result, expected: ${expected_sorted}, actual ${actual_sorted}"
            exit 1
          fi
        }

        json_actual_str=$(echo '${{ inputs.relevant-files-actual }}')
        json_expected_str=$(echo '${{ inputs.relevant-files-actual }}')
        is_array=$(echo "$json_actual_str" | jq --raw-output 'if type=="array" then "yes" else "no" end')

        echo "result is array? $is_array"

        if [ "$is_array" = "no" ]
        then
          validate_file_list $json_actual_str $json_expected_str
        else
          echo "we have an array"

          readarray -t actual_arr < <(echo "$json_actual_str" | jq -c '.[]')
          readarray -t expected_arr < <(echo "$json_expected_str" | jq -c '.[]')

          for i in "${!expected_arr[@]}"; do
            printf "expected: %s, actual: %s\n" "${expected_arr[i]}" "${actual_arr[i]}"
          done
        fi
