name: Automated tests
on: [pull_request, workflow_dispatch]
jobs:
  includes-excludes-is-relevant-yes:
    runs-on: ubuntu-latest
    outputs:
      relevant: "${{ steps.is-relevant.outputs.relevant }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check relevance
        id: is-relevant
        uses: ./
        with:
          filenames: "/aaa/bbb/ccc,/aaa/xxx.foo,/zzz/xxx.foo"
          includes: |
            aaa/**
            **/*.foo
          excludes: |
            /zzz/**
      - name: Validate is-relevant output
        uses: ./.github/actions/validate-output
        with:
          relevant-expected: "\"yes\""
          relevant-actual: ${{ steps.is-relevant.outputs.relevant }}
          relevant-files-expected: "\"/aaa/bbb/ccc,/aaa/xxx.foo\""
          relevant-files-actual: ${{ steps.is-relevant.outputs.relevant-files }}

  includes-is-relevant-yes:
    runs-on: ubuntu-latest
    outputs:
      relevant: "${{ steps.is-relevant.outputs.relevant }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check relevance
        id: is-relevant
        uses: ./
        with:
          filenames: "/aaa/bbb/ccc,/aaa/xxx.foo,/zzz/xxx.foo"
          includes: |
            /zzz/**
      - name: Validate is-relevant output
        uses: ./.github/actions/validate-output
        with:
          relevant-expected: "\"yes\""
          relevant-actual: ${{ steps.is-relevant.outputs.relevant }}
          relevant-files-expected: "\"/zzz/xxx.foo\""
          relevant-files-actual: ${{ steps.is-relevant.outputs.relevant-files }}

  includes-is-relevant-no:
    runs-on: ubuntu-latest
    outputs:
      relevant: "${{ steps.is-relevant.outputs.relevant }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check relevance
        id: is-relevant
        uses: ./
        with:
          filenames: "/aaa/bbb/ccc"
          includes: |
            /bbb/**
      - name: Validate is-relevant output
        uses: ./.github/actions/validate-output
        with:
          relevant-expected: "\"no\""
          relevant-actual: ${{ steps.is-relevant.outputs.relevant }}
          relevant-files-expected: "\"\""
          relevant-files-actual: ${{ steps.is-relevant.outputs.relevant-files }}

  excludes-is-relevant-yes:
    runs-on: ubuntu-latest
    outputs:
      relevant: "${{ steps.is-relevant.outputs.relevant }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check relevance
        id: is-relevant
        uses: ./
        with:
          filenames: "/aaa/bbb/ccc,/aaa/xxx.foo,/zzz/xxx.foo"
          excludes: |
            **/zzz/**
      - name: Validate is-relevant output
        uses: ./.github/actions/validate-output
        with:
          relevant-expected: "\"yes\""
          relevant-actual: ${{ steps.is-relevant.outputs.relevant }}
          relevant-files-expected: "\"/aaa/bbb/ccc,/aaa/xxx.foo\""
          relevant-files-actual: ${{ steps.is-relevant.outputs.relevant-files }}

  extglob-is-relevant-yes:
    runs-on: ubuntu-latest
    outputs:
      relevant: "${{ steps.is-relevant.outputs.relevant }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check relevance
        id: is-relevant
        uses: ./
        with:
          filenames: "file.ts,file.tsx,file.js,file.jsx,tile.txt"
          includes: "**/*.{t,j}s?(x)"
      - name: Validate is-relevant output
        uses: ./.github/actions/validate-output
        with:
          relevant-expected: "\"yes\""
          relevant-actual: ${{ steps.is-relevant.outputs.relevant }}
          relevant-files-expected: "\"file.ts,file.tsx,file.js,file.jsx\""
          relevant-files-actual: ${{ steps.is-relevant.outputs.relevant-files }}

  multi-is-relevant:
    runs-on: ubuntu-latest
    outputs:
      relevant: "${{ steps.is-relevant.outputs.relevant }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check relevance
        id: is-relevant
        uses: ./
        with:
          filenames: "/aaa/bbb/ccc,/aaa/xxx.foo,/zzz/xxx.foo"
          config: |
            [{
              "name": "A",
              "includes": "/aaa/**"
            }, {
              "name": "B",
              "includes": "/bbb/**"
            }, {
              "name": "C",
              "includes": "/**/bbb/**"
            }, {
              "name": "D",
              "includes": "/zzzz/**"
            }]
      - name: Validate is-relevant output
        uses: ./.github/actions/validate-output
        with:
          relevant-expected: "[\"yes\",\"no\",\"yes\",\"no\"]"
          relevant-actual: ${{ steps.is-relevant.outputs.relevant }}
          relevant-files-expected: "[\"/aaa/xxx.foo,/aaa/bbb/ccc\", \"\", \"/aaa/bbb/ccc\", \"\"]"
          relevant-files-actual: ${{ steps.is-relevant.outputs.relevant-files }}

  output-is-relevant-results:
    runs-on: ubuntu-latest
    needs:
      [
        includes-excludes-is-relevant-yes,
        includes-is-relevant-yes,
        excludes-is-relevant-yes,
      ]
    steps:
      - run: |
          echo 'using includes & excludes, expected is relevant yes: ${{ needs.includes-excludes-is-relevant-yes.outputs.relevant }}'
          echo 'only using includes, expected is relevant yes: ${{ needs.includes-is-relevant-yes.outputs.relevant }}'
          echo 'only using excludes, expected is relevant yes: ${{ needs.excludes-is-relevant-yes.outputs.relevant }}'
